### ISSUE TITLE
Windows binary

### ISSUE THREAD

**Issue by sergeevabc** [didenko/mboxrd#7]
Dear Vlad,
Could you be so kind to generate ```.exe``` for the rest of us who are mere Windows users w/o compiler?

**Comment by sergeevabc** [comment]
Err… Hello?

**Comment by didenko** [comment]
Unfortunately, I lack the time and Windows access to build and test the `.exe` binary. This project addressed a one-off need for me and I have no immediate plans putting more effort into the project. To make any kind of new release the code will have to be tested against the current Takeout downloads files which might have changed subtly but importantly.
